###
POST https://api.remove.bg/v1.0/removebg
X-Api-Key: 1iHxMgoQAgdc68uGSFTiLRGo
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image_file"; filename="camisa-rayas.jpg"
Content-Type: image/png

< ./images/camisa-rayas.jpg
--boundary--

###