# @BASE_URL=https://api.frankgp.com
# @BASE_URL=http://localhost:3000
@BASE_URL=http://localhost:8000
# @BASE_URL=http://localhost:5000
# @BASE_URL=https://python.fgp.one
# @BASE_URL=https://api.appsystered.com
# @BASE_URL=http://3.137.211.145
# @BASE_URL=https://dev.frankgp.com
@BASE_URL=http://91.108.126.37
# @BASE_URL=rembg2.ivanageraldine.com


###
GET {{BASE_URL}}/ping


###
GET {{BASE_URL}}/status


### 1) PNG sin compresión ni redimensionar
POST {{BASE_URL}}/v2.0/removebg?format=png
X-Api-Key: MY_API_KEY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image_file"; filename="image-2k.png"
Content-Type: image/png

< ./images/image-2k.png
--boundary--


### 2) JPEG con compresión
POST {{BASE_URL}}/v2.0/removebg?format=jpeg&compress_image=true
X-Api-Key: MY_API_KEY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image_file"; filename="image-2k.png"
Content-Type: image/png

< ./images/image-2k.png
--boundary--


### 3) PNG redimensionado a 640px ancho máximo
POST {{BASE_URL}}/v2.0/removebg?format=png&max_height=640
X-Api-Key: MY_API_KEY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image_file"; filename="image-2k.png"
Content-Type: image/png

< ./images/image-2k.png
--boundary--


### 4) JPEG comprimido + redimensionado
POST {{BASE_URL}}/v2.0/removebg?format=jpeg&compress_image=true&max_height=640
X-Api-Key: MY_API_KEY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image_file"; filename="image-2k.png"
Content-Type: image/png

< ./images/image-2k.png
--boundary--


### 5) WEBP con compresión
POST {{BASE_URL}}/v2.0/removebg?format=webp&compress_image=true
X-Api-Key: MY_API_KEY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image_file"; filename="image-2k.png"
Content-Type: image/png

< ./images/image-2k.png
--boundary--


### 6) WEBP redimensionado a 640 px
POST {{BASE_URL}}/v2.0/removebg?format=webp&max_height=640
X-Api-Key: MY_API_KEY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image_file"; filename="image-2k.png"
Content-Type: image/png

< ./images/image-2k.png
--boundary--


### v1.0
POST {{BASE_URL}}/v1.0/removebg
X-Api-Key: MY_API_KEY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image_file"; filename="image-2k.png"
Content-Type: image/png

< ./images/image-2k.png
--boundary--


###
GET {{BASE_URL}}/authTest
Authorization: Bearer my_secret_token