### python 1
POST https://python.fgp.one/v2.0/removebg?format=png
X-Api-Key: MY_API_KEY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image_file"; filename="image-2k.png"
Content-Type: image/png

< ./image-2k.png
--boundary--

### python 2
POST http://localhost:5000/v2.0/removebg?format=png
X-Api-Key: MY_API_KEY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image_file"; filename="image-2k.png"
Content-Type: image/png

< ./image-2k.png
--boundary--

### balancer
POST http://localhost:3000/v2.0/removebg?format=png
X-Api-Key: MY_API_KEY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image_file"; filename="image-2k.png"
Content-Type: image/png

< ./image-2k.png
--boundary--